version: "2.15.1"
services:
  db:
    image: postgres:12
    volumes:
      - type: volume
        source: postgresdb-data
        target: /Users/zato4en/Library/Application\Support/Postgres/var-15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zato4en
      POSTGRES_DB: bmstu
      POSTGRES_PASSWORD: akashow1

volumes:
  postgresdb-data:
    driver: local
